export default {
  'PROJECT_TOKEN': '49da47036049887820271edc2abae06f',
  'GET_LOGIN_URL': 'platformLoginModule/login.do',
  'RETRIEVE_PASSWORD_URL': 'platformLoginModule/retrievePassword.do',
  'GETUSERLIST_URL': 'platformLoginModule/getUserList.do',
  'DEL_USER_URL': 'platformLoginModule/delUser.do',
  'REGISTER_USER_URL': 'platformLoginModule/register.do',
  'EDIT_USER_URL': 'platformLoginModule/editUser.do',
  'GET_AUTHORITIES_LIST_URL': 'platformAuthoritiesModule/getAuthoritiesList.do',
  'GET_AUTHORITY_LIST_URL': 'platformAuthoritiesModule/getAuthoritiesAll.do',
  'GET_AUTHORITY_LIST_BY_USER_ID_URL': 'platformAuthoritiesModule/getAuthoritiesAllByRole.do',
  'GET_AUTHORITIES_LIST_BY_USERID_URL': 'platformAuthoritiesModule/getAuthoritiesListByUserId.do',
  'GRANT_AUTHORITIES_LIST_BY_USERID_URL': 'platformAuthoritiesModule/grantAuthoritiesByUserId.do',
  'GET_SAVE_AUTHORITY_URL': 'platformAuthoritiesModule/addAuthorities.do',
  'GET_UPDATE_AUTHORITY_URL': 'platformAuthoritiesModule/editAuthorities.do',
  'GET_DELETE_AUTHORIZE_URL': 'platformAuthoritiesModule/delAuthorities.do',
  'GET_AUTHORITIES_BY_TYPE': 'platformAuthoritiesModule/getAuthoritiesByType.do',
  'GET_ROLE_LIST_URL': 'platformRoleModule/getRoleList.do',
  'GET_SAVE_ROLE_URL': 'platformRoleModule/addRole.do',
  'GET_UPDATE_ROLE_URL': 'platformRoleModule/editRole.do',
  'GET_AUTHORITY_LIST_BY_ROLEID_URL': 'platformRoleModule/getAuthoritiesList.do',
  'DISABLE_ROLE_URL': 'platformRoleModule/disableRole.do',
  'GET_AUTHORITIES_ALL_BY_ROLE_ID_URL': 'platformAuthoritiesModule/getAuthoritiesAllByRoleId.do',
  'GET_ROLE_BY_USER_ID': 'platformRoleModule/getRoleByUserId.do',
  'EDIT_USER_ROLE_URL': 'platformRoleModule/editUserRole.do'
}
